# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ruby on Rails, Angular and mobile development team | Zegetech
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Zegetech is an Agile team with excellent track record &amp;
  great communication skills. We love Ruby on Rails,
  Angular and mobile development! Ping us!
keywords: >
  ruby rails angular zege technologies agile sprint
  MPESA safaricom fintech software developer nairobi
  freelancer kenya mobile developer android ios
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zegetech.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

timezone: Africa/Nairobi
# Build settings
permalink: /blog/:year/:month/:day/:title:output_ext
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - docker-compose.yml
include: ['_pages']
collections:
  projects:
    output: true
  blog:
    output: true
  # - clients
sitemap:
  filename: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
# # Where things are
# source:      .
# destination: ./_site
# plugins_dir:     ./_plugins
# # layouts_dir:     ./_layouts
# data_dir: ./_data
# # collections: null
# # include: ['_pages']

# configure relative links
relative_links:
  enabled: true
  collections: true

# Disqus Comments
disqus:
    shortname: zegetech

# jekyll-compose
# title and date are added by default
jekyll_compose:
  post_default_front_matter:
    layout: blog
    categories:
    published: false
    author:
    blog-image:
    intro:

algolia:
  application_id: TN8603H0T3
  index_name: zegetech.com
  search_only_api_key: 81daa33178cad0ab2dbe734196b5dccb
