# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ruby on Rails Software developement &amp; consultancy | Zege Technologies
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  FULLSTACK SOFTWARE DEVELOPMENT CONSULTANCY
  DEVELOP AMAZING PRODUCTS. FAST
  unlock your business technology potential
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zegetech.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - octopress-paginate
  # - jekyll-paginate
# paginate: 5
# paginate_path: "/news/page:num/"
exclude:
  - Gemfile
  - Gemfile.lock
include: ['_pages']
collections:
  projects:
    output: true
  news:
    output: true
  # - clients
sitemap:
  filename: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
# # Where things are
# source:      .
# destination: ./_site
# plugins_dir:     ./_plugins
# # layouts_dir:     ./_layouts
# data_dir: ./_data
# # collections: null

# # include: ['_pages']
